"""Command discovery: read metadata from command.py WITHOUT executing it.

Scripts are arbitrary code. Scanning happens at startup, for every folder the
user has, including ones they just received from someone else — so the scanner
never `exec`s IN THIS PROCESS. It reads the AST instead.

The one exception, and its boundary: a command that declares
`@tapioca.command(inputs=SomeModel)` keeps its ports in a class body, which no
AST pass can read — the model's JSON Schema exists only once the module has run.
Those ports are generated by importing the module in a SUBPROCESS
(`evp._schemagen`, cached by `evp._schemacache`), so the palette's own process
still never executes a command, a module that hangs cannot hang Rescan, and a
module that dies still yields a diagnostic instead of taking the scan with it.
Everything else on this page is still read statically, including that
command's title, category and selection sets — so a command whose import fails
still APPEARS in the palette, with its error, rather than vanishing.

That forces a CANONICAL FORM on the entry file (and only the entry file):
  * `import evp` or `import tapioca` — unaliased, so the decorator is
    recognisable statically
  * `@evp.command(...)` with LITERAL arguments — no f-strings, no names, no
    calls. `inputs=`/`outputs=`/`plan=` are the exception: they NAME a class or
    function in the module, and are recorded as that identifier
  * on a top-level `def run(...)`
Helpers in the folder are unrestricted. This is a feature of the format, like
pyproject.toml being TOML.

FAIL LOUDLY, NEVER SILENTLY: a folder that looks like a command but does not parse
to valid metadata appears in the palette's diagnostics with the reason and the
line number — never as a silent omission. A command you cannot see is worse than
one that reports why it is broken.
"""

import ast
import json
import math
import os
import re


class ScanError(Exception):
    def __init__(self, message, line=0):
        self.message = message
        self.line = line
        super().__init__(message)


_VERSION_CLAUSE = re.compile(r"(>=|<=|==|=|>|<)\s*(\d+(?:\.\d+){0,2})$")


def _validate_version_requirement(value, name, line):
    """Require a small, explicit semver-AND range readable by the C++ preflight."""
    if value is None:
        return None
    if not isinstance(value, str) or not value.strip():
        raise ScanError("@evp.command(%s=...) must be a non-empty semver range "
                        "such as \">=1.5.2\" (line %d)" % (name, line), line)
    clauses = [clause.strip() for clause in value.replace(",", " ").split() if clause.strip()]
    if not clauses or any(_VERSION_CLAUSE.fullmatch(clause) is None for clause in clauses):
        raise ScanError("@evp.command(%s=...) must be semver comparisons joined by spaces, "
                        "e.g. \">=1.5.2 <2.0.0\" (line %d)" % (name, line), line)
    return " ".join(clauses)


def _literal(node, what):
    """A decorator argument must be a literal — that is what makes it readable
    without running the module."""
    try:
        return ast.literal_eval(node)
    except (ValueError, SyntaxError):
        raise ScanError(
            "%s is not a literal (line %d). @evp.command arguments must be literals "
            "so the scanner can read them without executing the script."
            % (what, getattr(node, "lineno", 0)),
            getattr(node, "lineno", 0),
        ) from None


def _json_literal(value, what, line):
    """Accept only values JSON can represent exactly and safely."""
    def validate(item):
        if item is None or isinstance(item, (str, bool, int)):
            return
        if isinstance(item, float):
            if not math.isfinite(item):
                raise TypeError
            return
        if isinstance(item, list):
            for child in item:
                validate(child)
            return
        if isinstance(item, dict):
            for key, child in item.items():
                if not isinstance(key, str):
                    raise TypeError
                validate(child)
            return
        raise TypeError

    try:
        validate(value)
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
    except (TypeError, ValueError):
        raise ScanError(
            "%s must be an AST-literal JSON-compatible object (line %d)" % (what, line), line
        ) from None


def _is_command_decorator(node, namespaces, direct_command):
    """Match the supported static command decorator spellings."""
    if not isinstance(node, ast.Call):
        return False
    func = node.func
    if direct_command and isinstance(func, ast.Name) and func.id == "command":
        return True
    return (
        isinstance(func, ast.Attribute)
        and func.attr == "command"
        and isinstance(func.value, ast.Name)
        and func.value.id in namespaces
    )


def _describe_annotation(node):
    """Render a parameter's type for the dialog generator, statically.

    Returns (kind, extra). Unknown annotations are reported as-is rather than
    guessed at — P3 decides what it can build a control for.
    """
    if node is None:
        return "any", {}
    if isinstance(node, ast.Name):
        return node.id, {}                       # bool / int / float / str
    if isinstance(node, ast.Attribute):          # evp.Layer, evp.Story, ...
        return node.attr, {}
    if isinstance(node, ast.Call):               # evp.Float(unit="m2"), evp.Enum("a","b")
        func = node.func
        name = func.attr if isinstance(func, ast.Attribute) else getattr(func, "id", "?")
        extra = {}
        args = []
        for arg in node.args:
            try:
                args.append(ast.literal_eval(arg))
            except (ValueError, SyntaxError):
                raise ScanError(
                    "annotation argument is not a literal (line %d)" % node.lineno, node.lineno
                ) from None
        if args:
            extra["args"] = args
        for kw in node.keywords:
            try:
                extra[kw.arg] = ast.literal_eval(kw.value)
            except (ValueError, SyntaxError):
                raise ScanError(
                    "annotation argument '%s' is not a literal (line %d)" % (kw.arg, node.lineno),
                    node.lineno,
                ) from None
        if name == "FilePath":
            mode = extra.get("mode", "open")
            if mode not in ("open", "save"):
                raise ScanError(
                    "FilePath mode must be 'open' or 'save' (line %d)" % node.lineno,
                    node.lineno,
                )
            extensions = extra.get("extensions", ())
            if not isinstance(extensions, (list, tuple)) or any(
                not isinstance(extension, str)
                or not extension.lstrip(".")
                or "/" in extension
                or "\\" in extension
                for extension in extensions
            ):
                raise ScanError(
                    "FilePath extensions must be a literal list or tuple of file suffixes "
                    "(line %d)" % node.lineno,
                    node.lineno,
                )
        return name, extra
    return "any", {}


# Decorator arguments that name something in the module rather than carrying a
# value. They are stored as the IDENTIFIER; resolving them needs the module.
_MODEL_ARGS = ("inputs", "outputs", "plan", "preview")


def _model_name(node, arg, line):
    """The dotted name an inputs=/outputs=/plan= argument refers to.

    A bare name (`inputs=Inputs`) or an attribute path (`inputs=shapes.Inputs`).
    Anything computed is refused: the scanner would have to run it to find out
    what it is, and the whole contract here is that reading a command never
    executes it.
    """
    parts = []
    cursor = node
    while isinstance(cursor, ast.Attribute):
        parts.append(cursor.attr)
        cursor = cursor.value
    if not isinstance(cursor, ast.Name):
        raise ScanError(
            "@evp.command(%s=...) must name a class or function defined in this "
            "module, e.g. %s=Inputs (line %d). A computed value would have to be "
            "executed to be read, and reading a command never runs it."
            % (arg, arg, line), line)
    parts.append(cursor.id)
    return ".".join(reversed(parts))


def _check_schema_run_signature(fn, line):
    """A command that declares inputs= must take exactly (ctx, inputs).

    Annotating run()'s parameters as well would give the same control two
    sources — the model and the signature — and nothing downstream could say
    which one the palette drew. So the signature is fixed, and a stray extra
    parameter is a scan diagnostic rather than a control that never appears.
    """
    args = fn.args
    if args.vararg or args.kwarg:
        raise ScanError(
            "run() must not take *args/**kwargs (line %d)" % line, line)
    names = [a.arg for a in args.posonlyargs + args.args + args.kwonlyargs]
    if names != ["ctx", "inputs"]:
        raise ScanError(
            "a command with inputs= must define run(ctx, inputs), not run(%s) "
            "(line %d). The ports are the model's; annotating the signature too "
            "would give one control two sources."
            % (", ".join(names) or "", line), line)


def _parse_run_signature(fn):
    params = []
    args = fn.args

    if args.vararg or args.kwarg:
        raise ScanError(
            "run() must not take *args/**kwargs (line %d): every parameter needs a "
            "name and a type so the dialog can be generated." % fn.lineno,
            fn.lineno,
        )

    positional = args.posonlyargs + args.args
    defaults = list(args.defaults)
    # Defaults bind to the TAIL of the positional list.
    offset = len(positional) - len(defaults)

    for i, arg in enumerate(positional):
        kind, extra = _describe_annotation(arg.annotation)
        entry = {"name": arg.arg, "type": kind}
        if extra:
            entry.update(extra)
        if i >= offset:
            entry["default"] = _literal(defaults[i - offset], "default for '%s'" % arg.arg)
            entry["required"] = False
        else:
            entry["required"] = True
        params.append(entry)

    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        kind, extra = _describe_annotation(arg.annotation)
        entry = {"name": arg.arg, "type": kind}
        if extra:
            entry.update(extra)
        if default is not None:
            entry["default"] = _literal(default, "default for '%s'" % arg.arg)
            entry["required"] = False
        else:
            entry["required"] = True
        params.append(entry)

    return params


def _value_text(value):
    """One show_when value, spelled the way the palette spells a live control.

    A checkbox reads back as "true"/"false" on the C++ side, so `show_when=
    {"dry_run": False}` has to normalise to the same string here — otherwise the
    comparison never matches and the row simply never appears.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _choices_of(param):
    """The values a parameter can hold, or None when it can hold anything.

    Only the closed types answer: an Action's/Enum's own choices, and a bool's two
    states. A show_when against an open type (a text field, a layer picker) is
    legal — it just cannot be checked ahead of time.
    """
    if param["type"] in ("Action", "Enum"):
        return [str(c) for c in param.get("args", [])]
    if param["type"] in ("bool", "Bool"):
        return ["true", "false"]
    return None


def _fold_show_when(params, line):
    """Validate show_when and flatten it into two flat per-param keys.

    `show_when={"action": ["Place", "Update"]}` becomes

        "show_when_param":  "action"
        "show_when_values": ["Place", "Update"]

    for the same reason `labels` is folded per-param: the C++ side reads a param's
    metadata as a FLAT ObjectState of scalars and string arrays. A nested dict is
    the one shape it cannot read back, and it would arrive as nothing at all —
    a control that is always visible, with no error anywhere.

    Everything here fails LOUDLY. A show_when that names a parameter that does not
    exist, or a value its controller can never hold, produces a control the user
    can never see; as a diagnostic that is a five-second fix, and as silence it is
    an afternoon.
    """
    by_name = {p["name"]: p for p in params}

    actions = [p for p in params if p["type"] == "Action"]
    if len(actions) > 1:
        raise ScanError(
            "run() declares %d evp.Action parameters (%s), but a command has ONE "
            "mode (line %d). Use evp.Enum for a second choice — only the Action is "
            "pinned to the top of the block and reflows the inputs below it."
            % (len(actions), ", ".join(p["name"] for p in actions), line), line)
    for action in actions:
        if not action.get("args"):
            raise ScanError(
                "evp.Action('%s') declares no choices (line %d): evp.Action takes "
                "its modes as positional literals, e.g. "
                'evp.Action("Place", "Remove").' % (action["name"], line), line)

    # ⚠️ THE CHOICES ARE VARARGS, NOT A LIST. `evp.Enum(["a", "b"])` is a
    # perfectly good literal, so it scans, and it evaluates fine at runtime --
    # but it is ONE argument that happens to be a list, and the palette reads
    # `args` as a flat array of strings (ParamPanel: os.Get("args", choices)).
    # A nested array reads back as nothing, so the popup appears with NO OPTIONS
    # IN IT and the command cannot be driven at all. Caught live on 2026-08-10,
    # after the same annotation had already cost a round trip for a different
    # reason. Nothing downstream can tell the two spellings apart, so refuse the
    # wrong one here.
    for param in params:
        if param["type"] not in ("Action", "Enum"):
            continue
        for arg in param.get("args", []):
            if isinstance(arg, (list, tuple, set, dict)):
                raise ScanError(
                    "evp.%s('%s') was given a %s of choices (line %d). The choices "
                    "are POSITIONAL: evp.%s(\"a\", \"b\"), not evp.%s([\"a\", \"b\"]). "
                    "The list form runs fine but reaches the palette as a nested "
                    "array, and the popup appears EMPTY."
                    % (param["type"], param["name"], type(arg).__name__, line,
                       param["type"], param["type"]), line)
            if not isinstance(arg, str):
                raise ScanError(
                    "evp.%s('%s') has a non-string choice %r (line %d): a popup's "
                    "items are text. Spell numbers as strings."
                    % (param["type"], param["name"], arg, line), line)

    for param in params:
        spec = param.pop("show_when", None)
        if spec is None:
            continue
        if not isinstance(spec, dict) or len(spec) != 1:
            raise ScanError(
                "show_when on '%s' must be a dict naming exactly ONE controlling "
                'parameter, e.g. show_when={"action": "Place"} (line %d).'
                % (param["name"], line), line)
        controller, wanted = next(iter(spec.items()))
        if controller == param["name"]:
            raise ScanError(
                "'%s' has a show_when on itself (line %d): a control cannot decide "
                "whether it is visible." % (param["name"], line), line)
        if controller not in by_name:
            raise ScanError(
                "show_when on '%s' names '%s', which is not a parameter of run() "
                "(line %d). It would be a control that never appears."
                % (param["name"], controller, line), line)

        values = list(wanted) if isinstance(wanted, (list, tuple)) else [wanted]
        values = [_value_text(v) for v in values]
        if not values:
            raise ScanError(
                "show_when on '%s' lists no values (line %d)." % (param["name"], line), line)

        choices = _choices_of(by_name[controller])
        if choices is not None:
            unknown = [v for v in values if v not in choices]
            if unknown:
                raise ScanError(
                    "show_when on '%s' waits for '%s' to be %s, which it can never "
                    "be — its choices are %s (line %d)."
                    % (param["name"], controller, ", ".join(unknown),
                       ", ".join(choices) or "(none)", line), line)

        param["show_when_param"] = controller
        param["show_when_values"] = values


#: What each standard action's button SAYS. Here rather than in evp.outputs
#: because this module is loaded standalone by path in several places and cannot
#: import a sibling — and because the button text is palette metadata, which is
#: exactly what this file owns. evp.outputs owns the other half, what each action
#: DOES; test_outputs pins that the two name sets stay in step.
STANDARD_ACTION_LABELS = {
    "csv":       "Export CSV",
    "json":      "Export JSON",
    "text":      "Export text",
    "pdf":       "Export PDF",
    "png":       "Save image",
    "layout":    "Place on layout",
    "worksheet": "New worksheet",
    "bake":      "Bake",
}


def _custom_action_labels(tree):
    """{name: label} for every module-level function carrying @evp.action("...").

    Read statically, like everything else the palette needs: the button's text
    has to be available without executing the file, which is why the decorator's
    label must be a literal.
    """
    found = {}
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            call = decorator if isinstance(decorator, ast.Call) else None
            if call is None:
                continue
            target = call.func
            name = (target.attr if isinstance(target, ast.Attribute)
                    else getattr(target, "id", None))
            if name != "action" or not call.args:
                continue
            label = _literal(call.args[0], "@evp.action(...)")
            declared = node.name
            for keyword in call.keywords:
                if keyword.arg == "name":
                    declared = _literal(keyword.value, "@evp.action(name=...)")
            found[str(declared)] = str(label)
    return found


def _resolve_actions(meta, tree, line):
    """Turn `actions=[...]` plus the module's own @action functions into two flat
    parallel arrays: the names, and what each button says.

    Parallel arrays because C++ reads string arrays out of ObjectState reliably
    and nested objects it does not — the same reason `selection_sets` is flat.
    """
    custom = _custom_action_labels(tree)
    declared = meta.get("actions") or []
    if isinstance(declared, str) or not isinstance(declared, (list, tuple)):
        raise ScanError(
            "@evp.command(actions=...) must be a list of action names, e.g. "
            "[\"csv\", \"bake\"] (line %d)" % line, line)

    names, labels = [], []
    for name in list(declared) + [n for n in custom if n not in declared]:
        name = str(name)
        if name in STANDARD_ACTION_LABELS:
            labels.append(STANDARD_ACTION_LABELS[name])
        elif name in custom:
            labels.append(custom[name])
        else:
            raise ScanError(
                "@evp.command(actions=...) names %r, which is neither a standard "
                "action (%s) nor a function in this file decorated with "
                "@evp.action (line %d)"
                % (name, ", ".join(sorted(STANDARD_ACTION_LABELS)), line), line)
        names.append(name)

    meta["actions"] = names
    meta["action_labels"] = labels


# Where a right-click entry may appear. The palette resolves the region of the
# click itself (Palette/ControlPaletteMenu.cpp); this list is what an author is
# allowed to name, and naming anything else is a scan error rather than an entry
# that silently never shows.
MENU_REGIONS = ("panel", "params", "commands", "results")
MENU_PARAM_PREFIX = "param:"


def _custom_menu_items(tree):
    """[(name, label, region)] for every module-level function carrying
    @evp.menu("...") — in source order, which is the order they appear in.

    Read statically, like the action labels above and for the same reason: the
    palette has to build the menu without executing the file.
    """
    found = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            call = decorator if isinstance(decorator, ast.Call) else None
            if call is None:
                continue
            target = call.func
            name = (target.attr if isinstance(target, ast.Attribute)
                    else getattr(target, "id", None))
            if name != "menu" or not call.args:
                continue
            label = _literal(call.args[0], "@evp.menu(...)")
            declared = node.name
            region = "panel"
            for keyword in call.keywords:
                if keyword.arg == "name":
                    declared = _literal(keyword.value, "@evp.menu(name=...)")
                elif keyword.arg == "region":
                    region = _literal(keyword.value, "@evp.menu(region=...)")
            found.append((str(declared), str(label), str(region)))
    return found


def _resolve_menu(meta, tree, line):
    """Turn the module's @menu functions into three flat parallel arrays: the
    names run_action takes, what each entry says, and where it appears.

    Parallel arrays for the same reason `actions` uses them — C++ reads string
    arrays out of ObjectState reliably and nested objects it does not.

    A "param:<name>" region is checked against the command's OWN parameters here,
    where the line number is still known. A command whose ports come from a model
    (`inputs=`) has no statically readable parameters, so that check is skipped
    rather than guessed at.
    """
    declared_params = {str(p.get("name")) for p in (meta.get("params") or [])}
    schema_ports = bool(meta.get("inputs"))

    names, labels, regions = [], [], []
    for name, label, region in _custom_menu_items(tree):
        if region.startswith(MENU_PARAM_PREFIX):
            param = region[len(MENU_PARAM_PREFIX):]
            if not param:
                raise ScanError(
                    '@evp.menu(region="param:...") needs a parameter name after '
                    "the colon, e.g. \"param:offset\" (line %d)" % line, line)
            if not schema_ports and param not in declared_params:
                raise ScanError(
                    "@evp.menu(region=%r) names a parameter this command does not "
                    "declare. Declared: %s. An entry pinned to a control that does "
                    "not exist can never appear (line %d)"
                    % (region, ", ".join(sorted(declared_params)) or "none", line),
                    line)
        elif region not in MENU_REGIONS:
            raise ScanError(
                "@evp.menu(region=%r) is not a region. Use one of %s, or "
                '"param:<name>" for a single parameter\'s control (line %d)'
                % (region, ", ".join(MENU_REGIONS), line), line)
        names.append(name)
        labels.append(label)
        regions.append(region)

    meta["menu_items"] = names
    meta["menu_labels"] = labels
    meta["menu_regions"] = regions


def scan_file(path, folder_name):
    """Metadata for one command.py. Raises ScanError with a reason and a line."""
    with open(path, "r", encoding="utf-8") as handle:
        source = handle.read()

    try:
        tree = ast.parse(source, filename=path)
    except SyntaxError as e:
        raise ScanError("syntax error: %s (line %s)" % (e.msg, e.lineno), e.lineno or 0) from None

    namespaces = {
        alias.name
        for node in ast.walk(tree) if isinstance(node, ast.Import)
        for alias in node.names
        if alias.name in ("evp", "tapioca") and alias.asname is None
    }
    direct_command = any(
        isinstance(node, ast.ImportFrom) and node.module in ("evp", "tapioca")
        and any(alias.name == "command" and alias.asname is None for alias in node.names)
        for node in ast.walk(tree)
    )
    if not namespaces and not direct_command:
        raise ScanError(
            "command.py must contain plain `import evp`, `import tapioca`, or "
            "`from tapioca import command` (without aliases): the scanner recognises "
            "the decorator statically."
        )

    for node in tree.body:                     # top-level only, by contract
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name != "run":
            continue

        for decorator in node.decorator_list:
            if not _is_command_decorator(decorator, namespaces, direct_command):
                continue

            meta = {
                "title": folder_name,
                "category": "General",
                "requires_api": None,
                "requires_tapir": None,
                "runtime": "embedded",
                "description": None,
                "requires": [],
                # Extra search terms for the palette's search box. Never displayed,
                # so a command can carry the synonym, the other language and the
                # element type it works on without cluttering its title.
                "tags": [],
                # Preconditions the palette enforces BEFORE enabling Run, so a
                # command cannot be started in a state it will only fail in.
                "needs_selection": False,
                # E9 — seconds before the run cancels itself; 0 == no timeout.
                # Emitted as a float so the C++ side's Get() sees one type whether
                # the author wrote 30 or 30.0.
                "timeout_s": 0.0,
                # {param_name: "shown text"} — folded into each param below, then
                # dropped, so the C++ side only ever sees the flat per-param label.
                "labels": {},
                # Ordered role names for the optional selection-set panel. Kept flat
                # because C++ can reliably read string arrays from ObjectState.
                "selection_sets": [],
                # Explicit opt-in plus forced safety values for normal-run previews
                # triggered by complete selection-role changes.
                "preview_on_selection": False,
                "preview_overrides_json": "{}",
                # Which preview band to size, if any. "text" is the free one: the
                # Plan.diff() rendered into the results panel, no command code.
                # ALWAYS emitted, so the C++ side never has to guess at a default.
                "needs_preview": False,
                "preview_kind": "text",
                # Names from evp.outputs.STANDARD_ACTIONS the palette offers as
                # buttons under the results, and what each button says. Two flat
                # parallel arrays, same reason as above.
                "actions": [],
                "action_labels": [],
                # The command's own right-click entries: the names run_action
                # takes, what each says, and which region of the palette it
                # appears over. Three flat parallel arrays, same reason as above.
                # ALWAYS emitted, so a command with no menu reaches C++ as three
                # empty arrays rather than three missing keys.
                "menu_items": [],
                "menu_labels": [],
                "menu_regions": [],
            }
            if decorator.args:
                raise ScanError(
                    "@evp.command takes keyword arguments only (line %d)" % decorator.lineno,
                    decorator.lineno,
                )
            selection_sets_specified = False
            preview_overrides = None
            for kw in decorator.keywords:
                if kw.arg == "selection_sets":
                    selection_sets_specified = True
                # inputs=/outputs=/plan=/preview= name a MODEL or a function in the
                # same file, so they are the one place a decorator argument is
                # legitimately not a literal. Record the identifier; the ports
                # themselves come from the schema cache, which imports the module
                # in a subprocess (evp._schemagen). Everything else stays literal,
                # because the palette must be able to read it without executing.
                if kw.arg in _MODEL_ARGS:
                    meta[kw.arg] = _model_name(kw.value, kw.arg, decorator.lineno)
                    continue
                value = _literal(kw.value, "@evp.command(%s=...)" % kw.arg)
                if kw.arg == "preview_overrides":
                    preview_overrides = value
                    continue
                meta[kw.arg] = value

            # `timeout_s=30` is the natural way to write it, but the C++ reader asks
            # ObjectState for a double and a JSON integer is a different type to it —
            # the value would silently vanish and the timeout would never fire. Coerce
            # here, where the type is still ours to fix.
            try:
                meta["timeout_s"] = float(meta.get("timeout_s") or 0)
            except (TypeError, ValueError):
                raise ScanError(
                    "@evp.command(timeout_s=...) must be a number of seconds "
                    "(line %d)" % decorator.lineno, decorator.lineno)

            meta["requires_api"] = _validate_version_requirement(
                meta.get("requires_api"), "requires_api", decorator.lineno)
            meta["requires_tapir"] = _validate_version_requirement(
                meta.get("requires_tapir"), "requires_tapir", decorator.lineno)

            # Tags reach C++ as a flat array of strings, like `requires`. A single
            # string is the natural typo (tags="roof") and would otherwise arrive as
            # four one-character tags, matching nothing — so say it instead.
            tags = meta.get("tags") or []
            if isinstance(tags, str) or not isinstance(tags, (list, tuple)):
                raise ScanError(
                    "@evp.command(tags=...) must be a list of strings, e.g. "
                    '["roof", "slope"] (line %d)' % decorator.lineno, decorator.lineno)
            meta["tags"] = [str(t) for t in tags]

            selection_sets = meta.get("selection_sets") or []
            if (isinstance(selection_sets, str) or not isinstance(selection_sets, (list, tuple))
                    or (selection_sets_specified and not selection_sets)):
                raise ScanError(
                    "@evp.command(selection_sets=...) must be a list/tuple of role names, e.g. "
                    '("Targets", "Operators") (line %d)' % decorator.lineno, decorator.lineno)
            normalized = []
            seen = set()
            for role in selection_sets:
                if not isinstance(role, str) or not role.strip():
                    raise ScanError(
                        "@evp.command(selection_sets=...) role names must be non-empty strings "
                        "(line %d)" % decorator.lineno, decorator.lineno)
                key = role.strip().casefold()
                if key in seen:
                    raise ScanError(
                        "@evp.command(selection_sets=...) role names must be unique "
                        "(line %d)" % decorator.lineno, decorator.lineno)
                seen.add(key)
                normalized.append(role.strip())
            meta["selection_sets"] = normalized

            preview_on_selection = meta.get("preview_on_selection", False)
            if not isinstance(preview_on_selection, bool):
                raise ScanError(
                    "@evp.command(preview_on_selection=...) must be True or False "
                    "(line %d)" % decorator.lineno, decorator.lineno)
            if preview_overrides is None:
                preview_overrides = {}
            if not isinstance(preview_overrides, dict):
                raise ScanError(
                    "@evp.command(preview_overrides=...) must be a dict of forced parameter values "
                    "(line %d)" % decorator.lineno, decorator.lineno)
            if preview_on_selection and not normalized:
                raise ScanError(
                    "@evp.command(preview_on_selection=True) requires selection_sets=... "
                    "(line %d)" % decorator.lineno, decorator.lineno)
            if preview_on_selection and not preview_overrides:
                raise ScanError(
                    "@evp.command(preview_on_selection=True) requires non-empty preview_overrides=... "
                    "(line %d)" % decorator.lineno, decorator.lineno)
            meta["preview_overrides_json"] = _json_literal(
                preview_overrides, "@evp.command(preview_overrides=...)", decorator.lineno)
            _resolve_actions(meta, tree, decorator.lineno)

            if isinstance(node, ast.AsyncFunctionDef):
                raise ScanError("run() must not be async (line %d)" % node.lineno, node.lineno)

            if meta.get("inputs"):
                # A schema command's controls come from its Inputs model, not
                # from run(). The signature is fixed at (ctx, inputs) and carries
                # no annotations, so parsing it would produce two required
                # parameters the palette cannot render and Run would stay
                # disabled forever. The real ports arrive from the schema cache
                # (evp._schemagen), which imports the module in a subprocess.
                meta["params"] = []
                _check_schema_run_signature(node, decorator.lineno)
            else:
                meta["params"] = _parse_run_signature(node)
            for param in meta["params"]:
                if param.get("unit") in ("mm", "deg"):
                    api_unit = "m" if param["unit"] == "mm" else "rad"
                    api_name = "metres" if param["unit"] == "mm" else "radians"
                    raise ScanError(
                        "dimensional parameter '%s' uses unit=%r (line %d). Use API-base "
                        "unit=%r and express defaults/bounds in %s; the palette displays "
                        "the open project's Working Unit."
                        % (param["name"], param["unit"], decorator.lineno,
                           api_unit, api_name), decorator.lineno)

            # AFTER the parameters are parsed, because a "param:<name>" region is
            # checked against them — an entry pinned to a control that does not
            # exist is caught at Rescan rather than by a right-click that does
            # nothing.
            _resolve_menu(meta, tree, decorator.lineno)

            # Fold each localized label into its parameter's own metadata, so the
            # C++ dialog generator reads it flat (os.Get("label", ...)) — it cannot
            # reliably read a nested command-level dict. Then drop `labels`: it has
            # done its job and must not reach the flat JSON as a nested object.
            labels = meta.pop("labels", None) or {}
            if not isinstance(labels, dict):
                raise ScanError(
                    "@evp.command(labels=...) must be a dict of {param_name: text} "
                    "(line %d)" % decorator.lineno, decorator.lineno)
            for param in meta["params"]:
                if param["name"] in labels:
                    label = str(labels[param["name"]])
                    if param.get("unit") in ("m", "m2", "m3", "rad") and re.search(
                            r"\((?:m|mm|m[23]|mm[23]|cm[23]?|km[23]?|ft[23]?|in[23]?|yd[23]?|"
                            r"deg(?:rees)?|rad|°)\)\s*$", label, re.IGNORECASE):
                        raise ScanError(
                            "label for dimensional parameter '%s' hardcodes a unit (line %d). "
                            "Remove the suffix: the palette appends the open project's Working Unit."
                            % (param["name"], decorator.lineno), decorator.lineno)
                    param["label"] = label

            # F3 — the same folding, for the same reason: show_when arrives as a
            # nested dict and has to leave as flat keys the C++ side can read.
            _fold_show_when(meta["params"], node.lineno)

            meta["line"] = node.lineno
            return meta

        raise ScanError(
            "found a top-level `def run` but it has no @evp.command(...) decorator "
            "(line %d)" % node.lineno,
            node.lineno,
        )

    raise ScanError("no top-level `def run(...)` decorated with @evp.command(...) found")


def scan_root(root):
    """Scan one scripts root. Returns {"root":..., "commands":[...], "diagnostics":[...]}.

    A folder is a command if it contains command.py. Anything that looks like a
    command but does not parse lands in `diagnostics` WITH ITS REASON — never
    dropped silently.
    """
    commands = []
    diagnostics = []

    if not os.path.isdir(root):
        return {"root": root, "commands": [], "diagnostics": [
            {"folder": "", "error": "scripts root does not exist: %s" % root, "line": 0}
        ]}

    for name in sorted(os.listdir(root)):
        # `_`-prefixed folders are RESERVED, never commands: `_lib/` is the E4
        # shared-library slot (it goes on sys.path for every command under this
        # root), and the prefix is kept free for future tooling dirs. Skip them
        # explicitly so a stray `_lib/command.py` can never be scanned as a command
        # and shadow the very folder the runners put on sys.path.
        if name.startswith("_"):
            continue
        folder = os.path.join(root, name)
        entry = os.path.join(folder, "command.py")
        if not os.path.isdir(folder) or not os.path.isfile(entry):
            continue
        try:
            meta = scan_file(entry, name)
            meta["folder"] = name
            meta["path"] = entry
            if meta.get("inputs"):
                # The AST left params empty on purpose: this command's controls
                # live in its Inputs model and only exist once the module runs.
                #
                # Imported HERE, not at module scope: _scanner.py is loaded
                # standalone by path in several places (the offline scanner
                # tests, and any tool that wants the AST pass without the
                # package), and a module-level relative import makes that an
                # ImportError. The cache is only ever needed on this branch.
                from . import _schemacache

                generated = _schemacache.ports_for(folder)
                if generated.get("ok"):
                    if generated.get("params") is not None:
                        meta["params"] = generated["params"]
                    meta["needs_preview"] = generated.get("needs_preview", False)
                    meta["preview_kind"] = generated.get("preview_kind", "text")
                else:
                    # ⚠️ THE COMMAND STILL SHIPS. Its identity came from the AST
                    # and is intact; only its controls are missing. Raising here
                    # instead sent it to `diagnostics`, which the command LIST
                    # does not show — so a runtime that could not generate ports
                    # made the command DISAPPEAR, the exact failure this whole
                    # scanner is built to prevent, and it read as a failed build.
                    # Observed live: a misresolved interpreter cost a 30-second
                    # palette and a missing command in one go.
                    #
                    # The reason rides in the description because that is a
                    # surface the palette already renders; a new field would
                    # need a C++ change to be visible at all.
                    meta["params"] = []
                    meta["scan_error"] = generated.get("error", "unknown")
                    # ASCII ONLY. This string is generated by the scanner and
                    # travels to DG, to scan.log and through any console that
                    # happens to be attached — and a Windows console is cp1252,
                    # where one decorative glyph is a UnicodeEncodeError that
                    # would take the whole scan down. A command's own text may
                    # be Lithuanian; text this file invents stays ASCII.
                    meta["description"] = (
                        "INPUTS COULD NOT BE READ, so this command has no controls "
                        "and running it will fail. %s\n\n%s"
                        % (meta["scan_error"], meta.get("description") or ""))
            # `params` stays a list of dicts (readable in the log). `paramsJson`
            # is the same data as a list of JSON STRINGS, because that is the
            # only nested shape the C++ side can read: GS::Array<GS::ObjectState>
            # parsing is unproven in this codebase, arrays of strings are not.
            meta["paramsJson"] = [json.dumps(p) for p in meta["params"]]
            commands.append(meta)
        except ScanError as e:
            diagnostics.append({"folder": name, "error": e.message, "line": e.line})
        except OSError as e:
            diagnostics.append({"folder": name, "error": "cannot read command.py: %s" % e, "line": 0})

    # `commands`/`diagnostics` stay lists of dicts so the log is readable.
    # `commandsJson`/`diagnosticsJson` are the SAME data as lists of JSON STRINGS,
    # because that is the only nested shape the C++ side can read back:
    # GS::Array<GS::ObjectState> parsing is unproven in this codebase, whereas
    # GS::Array<GS::UniString> is proven (steps, bindings, and these).
    return {
        "root": root,
        "commands": commands,
        "diagnostics": diagnostics,
        "commandsJson": [json.dumps(c) for c in commands],
        "diagnosticsJson": [json.dumps(d) for d in diagnostics],
    }
