"""Cache the port metadata generated by importing a schema-style command.

Generating a command's ports means importing it (`evp._schemagen`), and
importing it means starting a subprocess. Doing that for 60+ folders on every
Rescan would turn a button press into several seconds of process launches, so
the result is cached and regenerated only when the command's own source
changes.

The cache key is the SHA-256 of every .py file in the command folder, not the
mtime: a `Sync-Commands.ps1` copy rewrites mtimes without changing content, and
a git checkout can move content without moving mtime. Hashing a command folder
is a few kilobytes of I/O and removes both failure modes.

⚠️ A cache MISS must never be fatal and must never be silent. A command whose
schema cannot be generated is reported as a scan diagnostic — the same place a
command with a syntax error lands — because a command that quietly disappears
from the palette looks exactly like a failed build.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys

from . import paths

__all__ = ["ports_for", "clear"]

_CACHE = "ports"
# A generated schema is a command's own module executing. It should take
# milliseconds; anything near this means the module is doing real work at import
# time, which is its own bug.
#
# ⚠️ This runs on the palette's Rescan path, which is a button press. The first
# version used 20s and resolved the interpreter wrongly, so every Rescan sat for
# the full timeout and the command vanished from the list — a 30-second palette
# and a missing command, from one misresolved path. Keep this SMALL: a scan that
# is slow is a scan people stop running.
_TIMEOUT_S = 6


def _interpreter():
    """The runtime's own python.exe, or None.

    ⚠️ NOT `sys.executable`. Inside Archicad this module runs in the EMBEDDED
    interpreter, whose `program_name` EvPPy.cpp sets to the literal "EvP" — so
    `sys.executable` is not a Python that can be launched, and handing it to
    subprocess buys a hang and then a timeout.

    `sys.prefix` is the runtime home, which is where `python.exe` lives; that is
    the same resolution `Python/ExternalRunner.cpp` uses for Zone C
    (`runtimeHome + "\\python.exe"`). base_prefix covers a venv, and
    `sys.executable` is the last resort for an ordinary interpreter running the
    offline tools.
    """
    names = ("python.exe", "python") if os.name == "nt" else ("python3", "python")
    for root in (sys.prefix, getattr(sys, "base_prefix", None)):
        if not root:
            continue
        for name in names:
            candidate = os.path.join(root, name)
            if os.path.isfile(candidate):
                return candidate
    executable = sys.executable or ""
    if executable and os.path.basename(executable).lower().startswith("python"):
        return executable
    return None


def _fingerprint(folder):
    """A stable hash of every .py file in the folder, contents and names.

    Names are hashed too, because deleting a helper changes what the command
    imports without changing any surviving file's bytes.
    """
    digest = hashlib.sha256()
    # The GENERATOR's shape, not just the command's. A cache entry written before
    # _schemagen learned to emit a field would otherwise survive a package upgrade
    # and answer without it — a stale entry that looks exactly like a command that
    # never declared the field. Bump this whenever the generated shape changes.
    digest.update(b"schemagen=2")
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".py"):
            continue
        digest.update(name.encode("utf-8"))
        try:
            with open(os.path.join(folder, name), "rb") as handle:
                digest.update(handle.read())
        except OSError as exc:
            # An unreadable source file is a real condition, not a cache miss:
            # fold it into the key so it cannot be mistaken for an unchanged
            # folder on the next pass.
            digest.update(repr(exc).encode("utf-8"))
    return digest.hexdigest()


def _cache_path(folder):
    """One cache file per folder PATH, not per folder name.

    The repo copy and the deployed copy of a command share a basename, and the
    offline gate scans one while Archicad scans the other. Keyed by name alone
    they would fight over a single file and each invalidate the other's entry on
    every run — a permanent cache miss that looks like the cache not working.
    """
    normalized = os.path.normcase(os.path.abspath(folder))
    tag = hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:12]
    return os.path.join(paths.cache_dir(_CACHE),
                        "%s-%s.json" % (os.path.basename(os.path.normpath(folder)), tag))


def ports_for(folder, package_root=None):
    """The command's generated ports, from cache or by importing it.

    Returns the `evp._schemagen.generate` payload:
    `{"ok": True, "params": [...] or None, "needs_preview": bool}` or
    `{"ok": False, "error": "..."}`. `params: None` means the command declares
    no inputs model, so the AST pass already has its ports.
    """
    fingerprint = _fingerprint(folder)
    path = _cache_path(folder)

    try:
        with open(path, encoding="utf-8") as handle:
            cached = json.load(handle)
        if cached.get("fingerprint") == fingerprint:
            return cached["result"]
    except (OSError, ValueError, KeyError):
        pass                          # a corrupt or absent cache just regenerates

    result = _generate(folder, package_root)

    # ⚠️ ONLY SUCCESS IS CACHED. The fingerprint covers the command folder, not
    # the environment, and the likeliest failure is environmental — a missing
    # pydantic, an unprovisioned runtime. Caching that would keep serving
    # "could not generate" after the user fixed it, because no file in the
    # folder changed. A broken command costs one subprocess per Rescan until it
    # works, and then stops costing anything.
    if result.get("ok"):
        try:
            with open(path, "w", encoding="utf-8") as handle:
                json.dump({"fingerprint": fingerprint, "result": result}, handle,
                          ensure_ascii=False)
        except OSError:
            # A cache that cannot be written is a slow Rescan, not a broken one.
            pass

    return result


def _generate(folder, package_root=None):
    """Run `python -m evp._schemagen <folder>` and read its JSON back."""
    root = package_root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    env = dict(os.environ)
    # PYTHONPATH, not sys.path manipulation in the child: the child is a fresh
    # interpreter that has not seen the add-on's staging, and `-m` needs the
    # package importable before it runs anything.
    env["PYTHONPATH"] = root + os.pathsep + env.get("PYTHONPATH", "")
    env["PYTHONIOENCODING"] = "utf-8"

    interpreter = _interpreter()
    if interpreter is None:
        return {"ok": False, "error": (
            "no python.exe beside the runtime (looked in %s). Run "
            "AddOn\\EvP\\Install-Runtime.ps1 to provision it." % sys.prefix)}

    # `-s` (ignore the user's site-packages) ONLY when we resolved an interpreter
    # other than the one running us — i.e. the Tapioca runtime. There it is the
    # same isolation Python/ExternalRunner.cpp applies, and it stops a stray
    # package in %APPDATA%\Python\Python312 from shadowing the runtime's own.
    # When the interpreter IS the current one (the offline gate, the tests) the
    # developer's environment is exactly what we want to see: `-s` there hid the
    # pydantic they had installed and reported the ports as ungeneratable.
    argv = [interpreter]
    if os.path.normcase(interpreter) != os.path.normcase(sys.executable or ""):
        argv.append("-s")
    argv += ["-m", "evp._schemagen", folder]

    try:
        completed = subprocess.run(
            argv,
            capture_output=True, text=True, encoding="utf-8",
            env=env, timeout=_TIMEOUT_S, check=False,
            # No console window: this runs from a DG button press inside
            # Archicad, and a flashing cmd box per command reads as a crash.
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": (
            "importing this command took longer than %ds. A command module "
            "should define things at import time, not do work - the palette "
            "reads it on every Rescan." % _TIMEOUT_S)}
    except OSError as exc:
        return {"ok": False, "error": "could not start the schema generator: %s" % exc}

    if completed.returncode != 0 or not completed.stdout.strip():
        detail = (completed.stderr or "").strip() or "no output"
        if "No module named 'pydantic'" in detail:
            # The most likely first-run failure, and the least guessable: the
            # baseline is applied by Install-Runtime.ps1 and by _env.reset(), so
            # a runtime provisioned before pydantic joined BASELINE does not
            # have it and nothing installs it retroactively.
            detail = ("pydantic is missing from the Tapioca runtime. Run\n"
                      "  \"%s\\python.exe\" -s \"<pkg>\\evp\\_env.py\" ensure "
                      "--require \"pydantic>=2.7,<3\"\n"
                      "or re-run AddOn\\EvP\\Install-Runtime.ps1." % sys.prefix)
        return {"ok": False, "error": "schema generator failed: %s" % detail}

    try:
        return json.loads(completed.stdout)
    except ValueError as exc:
        return {"ok": False,
                "error": "schema generator produced unreadable output: %s" % exc}


def clear():
    """Drop every cached schema. For the tests and for a manual Rescan."""
    directory = paths.cache_dir(_CACHE)
    for name in os.listdir(directory):
        if name.endswith(".json"):
            try:
                os.remove(os.path.join(directory, name))
            except OSError:
                pass
