"""Count the 3D mesh data generated by the current selection."""

import tapioca


@tapioca.command(
    title="Selection Geometry Inventory",
    category="Examples",
    description="Reports mesh, vertex, and triangle counts without copying mesh arrays.",
    needs_selection=True,
)
def run():
    if not tapioca.selection.get():
        tapioca.ui.text("Nothing is selected.")
        return

    snapshot = tapioca.geometry.snapshot(scope="selection")
    try:
        lines = ["Generated meshes: %d" % len(snapshot.meshes)]
        total_vertices = 0
        total_triangles = 0
        for mesh in snapshot.meshes:
            total_vertices += mesh.vertex_count
            total_triangles += mesh.triangle_count
            lines.append(
                "%s | type %d | %d vertices | %d triangles"
                % (mesh.guid, mesh.elem_type, mesh.vertex_count, mesh.triangle_count)
            )

        lines.extend([
            "",
            "Total vertices: %d" % total_vertices,
            "Total triangles: %d" % total_triangles,
        ])
        tapioca.ui.text("\n".join(lines))
    finally:
        snapshot.release()
